### ISSUE TITLE
Application doesn't start when using your converters

### ISSUE THREAD

**Issue by SuperJMN** [InquisitorJax/Wibci.Xamarin.Forms.Converters#3]
Hello! I tried you library, that seems to be a very good utility for almost any XamForms app.

However, I have a big problem with it:

I have a Xamarin Forms application whose App.xaml contains this XAML (inside the <Application>tag, of course)

```
    <Application.Resources>
        <ResourceDictionary>
            <converters:BooleanToInvertedBooleanConverter x:Key="BooleanToInvertedBooleanConverter" />
        </ResourceDictionary>
    </Application.Resources>
```

The application doesn't even start.

This doesn't happen if I use a converter I did myself.

What's going on?
Thanks.

**Comment by InquisitorJax** [comment]
Hi Jose,

I updated the sample app in the source to use resources defined in App.xaml - and it looks like everything works fine. 
tested using android: project reference - as well as nuget packages.

Some questions:
1) Are you calling InitializeComponent() in the App constructor?
2) Which platforms? 
perhaps you can repro in the sample app provided?

Malcolm

**Comment by InquisitorJax** [comment]
closing this. no response
